version: "3.7"
services:
    project-nginx:
        image: nginx:stable-alpine
        container_name: project-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - project-app
        networks:
            - project-network

    project-app:
        build:
            context: ./
            dockerfile: DockerFile
        container_name: project-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www
        ports:
            - 9000:80
        networks:
            - project-network

networks:
    project-network:
        driver: bridge
